name: Test VLESS and VMess Nodes with Xray

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  test-nodes:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests psutil

      - name: Run node tests
        run: |
          python test_nodes.py

      - name: List results dir
        run: ls -l results || echo "No results dir"

      - name: Upload valid nodes as artifact
        uses: actions/upload-artifact@v4
        with:
          name: valid_vless_configs
          path: results/valid_vless_configs.txt

      - name: Upload full ping test result log
        uses: actions/upload-artifact@v4
        with:
          name: ping_test_results
          path: results/ping_test_results.txt

      - name: Commit and push results to repository
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add results/valid_vless_configs.txt results/ping_test_results.txt
          git commit -m "Auto-update: Save latest valid VLESS configs and ping test results [skip ci]" || echo "Nothing to commit"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
